version: '3.7'

services:
  agent:
    container_name: superblocks-agent
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - SUPERBLOCKS_AGENT_KEY=${SUPERBLOCKS_AGENT_KEY}
    - SUPERBLOCKS_AGENT_HOST_URL=${SUPERBLOCKS_AGENT_HOST_URL}
    - SUPERBLOCKS_AGENT_ENVIRONMENT=${SUPERBLOCKS_AGENT_ENVIRONMENT}
    ports:
    - '8020:8020'
